### ISSUE TITLE
Convert all functions to 4.x API

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-extlib#113]
- [x] default_content
- [x] echo
- [x] ip_to_cron
- [x] extlib::has_module
- [x] extlib::sort_by_version
- [x] random_password [PR](https://github.com/voxpupuli/puppet-extlib/pull/112)
- [x] cache_data [PR](https://github.com/voxpupuli/puppet-extlib/pull/114)
- [x] dump_args [PR](https://github.com/voxpupuli/puppet-extlib/pull/118)
- [x] resources_deep_merge [PR](https://github.com/voxpupuli/puppet-extlib/pull/116)

Before a new (breaking/major) release, we could/should also...
- [x] Namespace all functions [PR](https://github.com/voxpupuli/puppet-extlib/pull/120)
- [x] Remove all function documentation from README and link to REFERENCE.MD [PR](https://github.com/voxpupuli/puppet-extlib/pull/121)
- [x] Rewrite [Limitations](https://github.com/voxpupuli/puppet-extlib/blob/master/README.md#limitations) section [PR](https://github.com/voxpupuli/puppet-extlib/pull/121)
- [x] Rewrite [Development](https://github.com/voxpupuli/puppet-extlib/blob/master/README.md#development) section [PR](https://github.com/voxpupuli/puppet-extlib/pull/121)

**Comment by bastelfreak** [comment]
I am fine with that

**Comment by alexjfisher** [comment]
Maybe we could do better...  Why not deprecate the non namespaced versions for a release or two.
See https://github.com/voxpupuli/puppet-extlib/pull/119
