### ISSUE TITLE
Module conflicts with puppetlabs/puppet_agent

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-extlib#148]
fact puppet_config is already provided by puppetlabs/puppet_agent module and represents path to the configuration file itself. IMHO fact should be renamed to puppet_settings

https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/lib/facter/settings.rb#L9-L13

**Comment by bastelfreak** [comment]
Hi @vchepkov, thanks for the issue! I renamed the fact in https://github.com/voxpupuli/puppet-extlib/pull/149

**Comment by vchepkov** [comment]
could you rename ruby file as well, please?
