### ISSUE TITLE
import add sorted_json function from  solarkennedy/puppet-consul

### ISSUE THREAD

**Issue by attachmentgenie** [voxpupuli/puppet-extlib#174]
can we add the sorted_json function here so that we can reference is from other module. aka the nomad module also depends on it. but instead of declaring the consul module as a dependency the code was copied as is but now trails with its updated

**Comment by ekohl** [comment]
Perhaps this should be a patch to https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/lib/puppet/functions/to_json.rb instead? Could be hidden behind a parameter if needed, but I think it makes sense in the wider community to have it in stdlib. Consistent JSON output is important in many places. extlib is really for things that aren't common or have some snags that make them harder to use in the wider community.

**Comment by attachmentgenie** [comment]
alright i have a look at extending that function instead
