### ISSUE TITLE
Add function to get the reverse from an IPv4/IPv6

### ISSUE THREAD

**Issue by bigon** [voxpupuli/puppet-extlib#228]
Hello,

It would be nice to have a function to get a reverse from an IPv4/IPv6

IPAddr ruby class has a function for this.

**Comment by alexjfisher** [comment]
We have a separate module for that.  See https://github.com/voxpupuli/puppet-dnsquery/blob/master/REFERENCE.md#dnsquery--ptr

**Comment by bigon** [comment]
@alexjfisher From what I understand the functions that you pointed to is doing the actual resolution? (note it should be more `dnsquery::rlookup()` in this case anyway) 

What I'm proposing is to calculate the reverse of an IP

like `10.1.2.42` => `42.2.1.10.in-addr.arpa` or `2001::dead:beef` => `f.e.e.b.d.a.e.d.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.2.ip6.arpa`

The function here should be merely a call to `IPAddr(ip).reverse`

**Comment by alexjfisher** [comment]
ah, ok.  Thanks for the clarification.  I'll reopen this issue.
