### ISSUE TITLE
import ip_to_cron

### ISSUE THREAD

**Issue by roidelapluie** [voxpupuli/puppet-extlib#48]
Does it make sense to integrate https://github.com/theforeman/puppet-puppet/blob/master/lib/puppet/parser/functions/ip_to_cron.rb ?

**Comment by jyaworski** [comment]
Have we talked to Foreman about it? The puppet-foreman module actually has extlib as a dependency.

**Comment by jyaworski** [comment]
Pinged @mmoll and @ekohl about it.

**Comment by mmoll** [comment]
I can't really say much here, personally I have no objections to have this moved into extlib and theforeman-puppet depending onto extlib, we just have to manage this somehow to not have a clash between the both.

Be aware that, as theforeman-puppet is under GPLv3 and extlib under Apache 2.0, this needs to get signed off by the original authors of that file.

**Comment by jyaworski** [comment]
Ping @mcanevet and @GregSutcliffe

**Comment by mmoll** [comment]
Sorry, I don't want to throw in a wrench here, but I suppose @roidelapluie opened this issue here at extlib to discuss **first**, if ip_to_cron could find a place in extlib (or not). **If** yes, the whole coordination with the respective persons can happen, but not before the decision has been made...

**Comment by jyaworski** [comment]
We're for it, sorry if that wasn't immediately clear.

**Comment by mmoll** [comment]
@jyaworski oh, ok. :) And that kids, is why you want to have such discussiona in the respective GH issues and not in IRC ;)

**Comment by jyaworski** [comment]
Staged in #49 once signoff is achieved. Do we have a policy if we don't hear from the original authors?

@igalic @daenney

**Comment by roidelapluie** [comment]
The policy is simple: it is impossible to do so without the sign off.

**Comment by daenney** [comment]
From my understanding of it this is a variant of `fqdn_rand` just based on the last octet of the IP address, correct? Looking at the code as it stands this will fail miserably on IPv6 only machines so we'd have to patch that up before landing it.

However, the original code in the Foreman Puppet module is licensed as GPLv3:
> However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.
http://www.apache.org/licenses/GPL-compatibility.html

As it stands we are not allowed to incorporate that snippet from their module. It should however be trivial to come up with our own implementation of this that we can license as APL2 which also fixes the aforementioned shortcomings w.r.t IPv6.

**Comment by roidelapluie** [comment]
@daenney that is why we wask for their agreement to relicense it

**Comment by daenney** [comment]
@roidelapluie Sure. However, if you don't get it there's the option to implement it yourself :smile:.

But yes, as you said, no signoff = no way forward. We can't just grab the code because the original authors couldn't be reached, that would be a violation.

**Comment by jyaworski** [comment]
@daenney maybe we should just reimplement it. It needs ipv6 anyway.

**Comment by jyaworski** [comment]
OK, I reinvented it a little bit in #49. Maybe take a look. I kept the name the same for consistency, even though it works slightly differently.

**Comment by nibalizer** [comment]
I want to be super clear that the GPL does not permit us to just ninja this into extlib. @jyaworski your github repo is also a problem since you've done that. I would remove the branch and discontinue work until you have the go-ahead from the authors.

**Comment by nibalizer** [comment]
I also am not a lawyer but I don't think we get to read their code, find a bug, then whip up a different implementation and call it good.

**Comment by jyaworski** [comment]
Forgive me for potentially not understanding.

I've done significant changes to the original code. What more has to be done before we can call this good? I'm not optimistic about hearing back from the original authors; the last commits to that file were in 2013.

**Comment by mmoll** [comment]
"significant changes to the original code" is **not** a new clean room implementation. **Please**, let's keep the discussion here in this issue (although apparently @mcanevet gave his OK for re-licensing in #49) and wait until @GregSutcliffe does give his permission (or not, which can happen, see theforeman/hammer-cli#147).

**Comment by igalic** [comment]
:+1: on waiting for @GregSutcliffe.

**Comment by GregSutcliffe** [comment]
Sorry guys, I did on #49 and forgot to do this one. Happy to re-license :+1:

**Comment by igalic** [comment]
awesome, thank you so much, @GregSutcliffe!

**Comment by domcleal** [comment]
@jyaworski would you mind organising [a release](https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module) of this module soon please?

**Comment by jyaworski** [comment]
@domcleal we'll cut a release once the fate of #53 is determined.
