### ISSUE TITLE
please make a fresh release

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-extlib#54]
After importing #48, we should make a fresh release.
*****
Should we declare this module stable, releasing 1.0.0?

**Comment by bastelfreak** [comment]
:+1: for a new release, there are no open issues. I'm also using many functions of the module in a big env and I'm not aware of any problems. IMO we can declare it as stable.

**Comment by jyaworski** [comment]
I think we should actually release, and then branch it off. We need to drop 1.8.7 support.

**Comment by igalic** [comment]
this module could be a good start for such experimental endeavours in release engineering…

**Comment by bastelfreak** [comment]
We did [a few releases](https://github.com/voxpupuli/puppet-extlib/releases) yesterday, the last one made it to the forge.
