### ISSUE TITLE
Add encrypted_cache_data function

### ISSUE THREAD

**Issue by edestecd** [voxpupuli/puppet-extlib#64]
We would like a cache_data function that acts exactly the same, but also encrypts the yaml files with eyaml.  This would be useful for us in a multi puppet master setup, so we can store the passwords on a nfs / shared storage without worrying about exposing passwords.

Would such a PR be desirable?  Interest?  Thoughts?

**Comment by mmckinst** [comment]
It seems like there's two problems you've described:

1. the ability specify the directory where the cache is stored (so you can use an nfs / shared mount)
2. the ability to encrypt stuff using eyaml

I would guess #1 wouldn't be a problem although I'm not a member of voxpupli. For #2, I think an encrypted_cache_data would be nice.

Regarding your problem in general, I've thought about solving that problem with hashicorp vault instead, but you'd have to add a function similar to cache_data for hashicorp vault first.

**Comment by edestecd** [comment]
@mmckinst 

1. You can already do this:
```puppet
cache_data('cache_date/mysql', 'mysql_password', 'this_is_my_password')
```

Yes vault is definitely the robust way to go.
Consequently, my organization has selected lastpass as our "official" password solution.
So, I will be writing a module to implement functions and a hiera backend to use last pass instead of this feature...

Naturally, it will be open source, so check it out if you are interested...
