### ISSUE TITLE
cache_data() stores data locally on puppetserver

### ISSUE THREAD

**Issue by pkranenburg** [voxpupuli/puppet-extlib#80]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: server 2.7  in multi-puppetserver configuration with load-balancer
- Ruby: AIO version
- Distribution: community
- Module version:

## How to reproduce (e.g Puppet code you use)
$password = cache_data('foreman_cache', 'postgres_db_passwd', getrandomstring())

## What are you seeing
Cached data is stored in the puppetserver's local file system (/opt/puppetlabs/server/data/....) from where it is only available to the same puppet server.  If a subsequent puppet agent run on the same client is served by another puppet server from the load-balancing pool, the supposedly cached data is not there, resulting in another (most likely, inconsistent) copy of data.

## What behaviour did you expect instead
For this function to be useful in multi-puppetserver environment, the data cache should located in a location accessible to all servers, for instance on common shared storage or in a PuppetDB table.

**Comment by ffrank** [comment]
At a glance, I don't see a way to store arbitrary data in PuppetDB.

Shared storage is an option. However, I don't see what we can do about it from within the module. The user can (and needs to) make sure that each namespace subdirectory of `vardir` is located on a shared storage.

Do you have concrete suggestions what we could add to this module to make it more appropriate in a multi-master context?

**Comment by DesideriusE** [comment]
I have nothing more than the suggestion to use some kind of common storage for the cached data.

As a minimum though, I suggest a documentation update that spells out the current limitations and ramifications, e.g.:

  1. in a multi-master environment, all class parameters that would default to generated-then-cached values SHOULD be explicitly specified
  2. even in a single-master environment, whenever updating or migrating a puppet server the data used by this caching mechanism MUST be migrated too lest surprising changes happen on your clients

**Comment by ffrank** [comment]
Agreed - these issues are best handled by some very explicit documentation (as there is little we can do to mitigate these limitations in code).

**Comment by ekohl** [comment]
The reason ```cache_data``` was submitted here and not stdlib was precisely because this limitation. A PR to state this would be highly appreciated

**Comment by ekohl** [comment]
It is now documented as a limitation.
